services:
  lakehouse:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    env_file: .env
    ports:
      - "3001:3000"
      - "8502:8501"
      - "8001:8000"
    stdin_open: true
    tty: true
    command: bash
